idf_component_register(
    SRCS
        "main.c"
        "spotify.c"
        "album_art.cpp"
        "littlefs.c"
    INCLUDE_DIRS "." "../include"
    PRIV_REQUIRES
        esp_http_client
        esp-tls
        mbedtls
        esp_timer
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        joltwallet__littlefs
        vfs
)
