# sync-to-private.ps1
#
# Copies the public IDF source tree to the private working copy so you
# can build with real credentials without ever committing them.
#
# Excluded from sync:
#   secrets.h          -- destination keeps its own real credentials
#   build/             -- regenerated by idf.py
#   managed_components/ -- regenerated by idf.py reconfigure
#
# Uses robocopy /MIR so new files are added, changed files are updated,
# and files you delete from the public tree are removed from the private
# copy too.  Re-running is idempotent.

param(
    [string]$SourceRoot = $PSScriptRoot,
    [string]$Dest = "C:\Users\lewis\Documents\Music Controller - Private\CYD-ESP-IDF"
)

$source = Join-Path $SourceRoot "cyd\esp-idf"

if (-not (Test-Path $source)) {
    Write-Error "Source not found: $source"
    exit 1
}

Write-Host "From : $source"
Write-Host "To   : $Dest"
Write-Host ""

robocopy $source $Dest /MIR /XD build managed_components .git /XF secrets.h /NP

$rc = $LASTEXITCODE
if ($rc -le 7) {
    Write-Host ""
    Write-Host "Done (robocopy exit $rc)."
} else {
    Write-Error "robocopy failed with exit code $rc."
    exit 1
}
