/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_HOME_CONTROLLER_PB_H_INCLUDED
#define PB_HOME_CONTROLLER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* P4 -> RP2040: configure haptic behaviour + LEDs */
typedef struct _KnobConfig {
    int32_t position; /* current logical position */
    float sub_position_unit;
    uint32_t position_nonce; /* increment to force re-apply same position */
    int32_t min_position; /* -1 = unbounded */
    int32_t max_position; /* -1 = unbounded */
    float position_width_radians; /* angular width per detent (e.g. 10 deg = 0.175 rad) */
    float detent_strength_unit; /* [0.0, 1.0] */
    float endstop_strength_unit;
    float snap_point; /* hysteresis threshold (e.g. 1.1) */
    pb_callback_t led_ring_rgbw; /* 4 bytes x 12 LEDs = 48 bytes (RGBW) */
    pb_callback_t button_led_rgbw; /* 4 bytes x 4 LEDs = 16 bytes */
} KnobConfig;

/* RP2040 -> P4: knob state events */
typedef struct _KnobState {
    int32_t current_position;
    float sub_position_unit;
    uint32_t press_nonce; /* strain-gauge button: increments on each press */
    uint32_t button_mask; /* bits 0-3: MX buttons (1 = pressed, active-low inverted) */
    int32_t battery_percent; /* from MAX17048 (0-100) */
    int32_t ambient_lux; /* from VEML7700 (for auto-brightness on P4) */
} KnobState;

/* Wrapper messages (same Ack/retry pattern as SmartKnob) */
typedef struct _ToKnob {
    uint32_t protocol_version;
    uint32_t nonce;
    pb_size_t which_payload;
    union {
        KnobConfig config;
        bool request_state;
    } payload;
} ToKnob;

typedef struct _FromKnob {
    uint32_t protocol_version;
    pb_size_t which_payload;
    union {
        uint32_t ack; /* echoes nonce */
        KnobState state;
        pb_callback_t log;
    } payload;
} FromKnob;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KnobConfig_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define KnobState_init_default                   {0, 0, 0, 0, 0, 0}
#define ToKnob_init_default                      {0, 0, 0, {KnobConfig_init_default}}
#define FromKnob_init_default                    {0, 0, {0}}
#define KnobConfig_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define KnobState_init_zero                      {0, 0, 0, 0, 0, 0}
#define ToKnob_init_zero                         {0, 0, 0, {KnobConfig_init_zero}}
#define FromKnob_init_zero                       {0, 0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define KnobConfig_position_tag                  1
#define KnobConfig_sub_position_unit_tag         2
#define KnobConfig_position_nonce_tag            3
#define KnobConfig_min_position_tag              4
#define KnobConfig_max_position_tag              5
#define KnobConfig_position_width_radians_tag    6
#define KnobConfig_detent_strength_unit_tag      7
#define KnobConfig_endstop_strength_unit_tag     8
#define KnobConfig_snap_point_tag                9
#define KnobConfig_led_ring_rgbw_tag             10
#define KnobConfig_button_led_rgbw_tag           11
#define KnobState_current_position_tag           1
#define KnobState_sub_position_unit_tag          2
#define KnobState_press_nonce_tag                3
#define KnobState_button_mask_tag                4
#define KnobState_battery_percent_tag            5
#define KnobState_ambient_lux_tag                6
#define ToKnob_protocol_version_tag              1
#define ToKnob_nonce_tag                         2
#define ToKnob_config_tag                        3
#define ToKnob_request_state_tag                 4
#define FromKnob_protocol_version_tag            1
#define FromKnob_ack_tag                         2
#define FromKnob_state_tag                       3
#define FromKnob_log_tag                         4

/* Struct field encoding specification for nanopb */
#define KnobConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    position,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    sub_position_unit,   2) \
X(a, STATIC,   SINGULAR, UINT32,   position_nonce,    3) \
X(a, STATIC,   SINGULAR, INT32,    min_position,      4) \
X(a, STATIC,   SINGULAR, INT32,    max_position,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    position_width_radians,   6) \
X(a, STATIC,   SINGULAR, FLOAT,    detent_strength_unit,   7) \
X(a, STATIC,   SINGULAR, FLOAT,    endstop_strength_unit,   8) \
X(a, STATIC,   SINGULAR, FLOAT,    snap_point,        9) \
X(a, CALLBACK, SINGULAR, BYTES,    led_ring_rgbw,    10) \
X(a, CALLBACK, SINGULAR, BYTES,    button_led_rgbw,  11)
#define KnobConfig_CALLBACK pb_default_field_callback
#define KnobConfig_DEFAULT NULL

#define KnobState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    current_position,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    sub_position_unit,   2) \
X(a, STATIC,   SINGULAR, UINT32,   press_nonce,       3) \
X(a, STATIC,   SINGULAR, UINT32,   button_mask,       4) \
X(a, STATIC,   SINGULAR, INT32,    battery_percent,   5) \
X(a, STATIC,   SINGULAR, INT32,    ambient_lux,       6)
#define KnobState_CALLBACK NULL
#define KnobState_DEFAULT NULL

#define ToKnob_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,config,payload.config),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (payload,request_state,payload.request_state),   4)
#define ToKnob_CALLBACK NULL
#define ToKnob_DEFAULT NULL
#define ToKnob_payload_config_MSGTYPE KnobConfig

#define FromKnob_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   ONEOF,    UINT32,   (payload,ack,payload.ack),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,state,payload.state),   3) \
X(a, CALLBACK, ONEOF,    STRING,   (payload,log,payload.log),   4)
#define FromKnob_CALLBACK pb_default_field_callback
#define FromKnob_DEFAULT NULL
#define FromKnob_payload_state_MSGTYPE KnobState

extern const pb_msgdesc_t KnobConfig_msg;
extern const pb_msgdesc_t KnobState_msg;
extern const pb_msgdesc_t ToKnob_msg;
extern const pb_msgdesc_t FromKnob_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KnobConfig_fields &KnobConfig_msg
#define KnobState_fields &KnobState_msg
#define ToKnob_fields &ToKnob_msg
#define FromKnob_fields &FromKnob_msg

/* Maximum encoded size of messages (where known) */
/* KnobConfig_size depends on runtime parameters */
/* ToKnob_size depends on runtime parameters */
/* FromKnob_size depends on runtime parameters */
#define HOME_CONTROLLER_PB_H_MAX_SIZE            KnobState_size
#define KnobState_size                           50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
