/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "home_controller.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(KnobConfig, KnobConfig, AUTO)


PB_BIND(KnobState, KnobState, AUTO)


PB_BIND(ToKnob, ToKnob, AUTO)


PB_BIND(FromKnob, FromKnob, AUTO)



